### PR TITLE
Updated the index.md

### PR DESCRIPTION
**Pull request by cesarecaoduro**
Updated the index.md file for the documentation

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [X] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR updates the index.md file generated with the documentation

### Related Tickets & Documents
No issues related

### Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by sonomirco** [comment]
Can we have the logo on the index page?
How do we want to treat these kinds of changes in terms of release/NuGet package?
Currently, if we merge this PR a new NuGet will be generated, is it worth having a new package for changes like this?

**Review by sonomirco — APPROVED** [review]

**Comment by cesarecaoduro** [comment]
I don’t think that this is worth a release. We have to find a mechanism to release only on version tags, or we have to split the documentation on a separate branch, potentially a separate repository.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sonomirco** [comment]
The release action generates the tag.
An implementation is that only PRs with labels `Major` or `Minor` creates a NuGet package; all the others add a new release in GitHub.

**Comment by cesarecaoduro** [comment]
> The release action generates the tag. An implementation is that only PRs with labels `Major` or `Minor` creates a NuGet package; all the others add a new release in GitHub.

We have to put some more thoughts around this. For now we can merge this small update.
Also considering the logo, we already have the logo on the sidebar, I don't think there is a need of another logo in the main content. 
We probably need to also spend some time styling the template, but it is not a priority (I will Open an issue for this)

**Comment by d3ssy** [comment]
Weren't the docs being generated from gshark/docs branch? I don't think users should have to touch the doc generation or need to download it with the main branch.

**Comment by sonomirco** [comment]
That is the brunch used to publish the doc, but the documentation is on the main repo, but I don't think is a problem.

**Pull request merged**
