### PR TITLE
Updated GitHub actions

### PR DESCRIPTION
**Pull request by sonomirco**
### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [ ] 🐛 Bug Fix
- [x] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR updates the GitHub actions.
A new NuGet API Token has been provided; it should fix the error we got with the last deployment.

### Related Tickets & Documents

There are no related tickets.

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by sonomirco** [comment]
@d3ssy @cesarecaoduro 
Some changes we could add to this PR.
- Can we remove the diagram and the relative action? Or do you think it is useful?
- Because we have the patch, minor, and major as labels, do we want to move from having alphas to semantic versioning? We could use the actual [release drafter](https://github.com/release-drafter/release-drafter) to generate the new version.

**Comment by d3ssy** [comment]
- Happy to remove diagram... i don't remember ever looking at it or making use of it.
- Yes, would like to get rid of alpha releases, also never used.
- Happy to get rid of NetCore 3.1 build target (i don't think we'll make anyone cry 😄 )
- Shall we move to trunk based development instead of gitflow to simplify the whole CI/CD pipeline?

**Comment by sonomirco** [comment]
Sounds good to me.
So every branch will be merged on main, dev will be removed and we will use semantic version.

**Comment by cesarecaoduro** [comment]
Good for me

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by d3ssy — APPROVED** [review]

**Comment by sonomirco** [comment]
@d3ssy and @cesarecaoduro 
Made all the changes.
Once we merge all the PRs, we can remove the development branch and start following trank-based development.
The actual checks build and test the solution every time a PR is created or updated in DotNet `3.1.x and 6.0.x`.
I thought to keep 3.1.x only for the checks in the meantime, DotNet 7 will be consolidated.

I made some changes in the ReadMe file and on the events which are hooked and published on Discord.

**Comment by cesarecaoduro** [comment]
Great job!
Thanks.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
